[Server]
ListenAddress = "127.0.0.1"
ListenPort = 8080
# This defines the address, bnv-manager is available for users.
# E.g.: https://manager.example.com or http://manager.example.com:8080
PublicURI = ""
# Add each host / domain this server should be accessed by.
# In scheme: https://manager.example.com
AllowedHosts = [
    "",
]
# You can set this to true, if bnv-manager is deployed behin a reverse proxy
# and therefore has no TLS configured. You can still set your AllowedHosts
# to enforce the use of https:// and add the X-Forwarded-Proto header on
# your reverse proxy.
UseForwardedProtoHeader = true

[BigBlueButton]
# URI of the BBB Server. Can be retrieved using `bbb-conf --secret`
ServerURI = "https://bbb.example.com/bigbluebutton/"
# Secret of the BBB Server. Can be retrieved using `bbb-conf --secret`
SharedSecret = ""
# Username to use when joining meetings
Username = "BBB Bot"

[Selenium]
# The path to the selenium-server.jar
SeleniumPath = ""
# The path to geckodriver
GeckoDriverPath = ""
# The path to firefox
FirefoxPath = ""
# The path to chromium
ChromiumPath = ""
# The path to chromedriver
ChromedriverPath = ""
# If true, chromium with chromedriver will be used. Otherwise firefox with geckodriver
UseChromium = true
# Set to true to disable headless running
DisableHeadless = false
# The number of running instances
InstanceCount = 4